### ISSUE TITLE
Job Annotation via REST

### ISSUE THREAD

**Issue by hashanp** [dalekjs/dalek-driver-sauce#11]
At the moment `dales-driver-sauce` does not report back to Sauce Labs on whether a test has passed or failed. This is needed to produce [status images](https://docs.saucelabs.com/reference/status-images/). This cannot be accomplished through Selenium, but can be accomplished through the [REST API](https://docs.saucelabs.com/reference/test-configuration/#job-annotation-with-the-rest-api). If someone could point me as to where this code would go and how to get the job id, I would be happy to send a pull request.

**Comment by asciidisco** [comment]
We´re rewriting the adapter atm.; I´m taking this with me as an open task.
